name: FizzBuzzActions

on:
  push: 
    branches: [ main ]  
  
jobs:
  
  build:
    runs-on: ubuntu-latest

    
    steps:

      - uses: actions/checkout@v1

      - name: pip install 
        run: sudo apt install pipenv

      - name: install   
        run: pipenv install

      - name: dev install   
        run: pipenv install --dev
      
      - name: lint
        run: pipenv run flake8

      - name: test
        run: pipenv run python -m pytest
      