name: FizzBuzzActions

on:
  push: 
    branches: [ main ]  
  
jobs:
  
  build:
    runs-on: ubuntu-latest

    
    steps:

      - uses: actions/checkout@v1

      - name: install 
        run: sudo apt install pipenv
      
      # - name: lint
      #   run: pipenv run flake8

      # - name: test
      #   run: pipenv run python -m pytest
      